name: Unity Content Manifest

on:
  push:
    branches: ["main", "master", "work"]
  pull_request:
    branches: ["main", "master", "work"]
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Generate manifest from content
        run: node scripts/generate-manifest.mjs

      - name: Verify manifest is up to date
        if: github.event_name == 'pull_request'
        run: |
          if ! git diff --quiet -- content/manifest.json; then
            echo "::error::manifest.json is outdated. Run 'node scripts/generate-manifest.mjs' and commit the result.";
            exit 1;
          fi

      - name: Commit manifest updates
        if: github.event_name != 'pull_request'
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: update content manifest"
          file_pattern: content/manifest.json
